import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002113",
        "tertiary": "#ffb2b7",
        "on-error": "#690005",
        "primary-fixed": "#6ffbbe",
        "tertiary-container": "#ff7886",
        "tertiary-fixed-dim": "#ffb2b7",
        "surface-container-low": "#0d1c2d",
        "on-secondary": "#472a00",
        "on-primary": "#003824",
        "secondary-fixed": "#ffddb8",
        "tertiary-fixed": "#ffdadb",
        "on-secondary-container": "#5b3800",
        "on-surface": "#d4e4fa",
        "on-surface-variant": "#bbcabf",
        "on-primary-fixed-variant": "#005236",
        "on-secondary-fixed-variant": "#653e00",
        "surface-bright": "#2c3a4c",
        "secondary": "#ffb95f",
        "inverse-primary": "#006c49",
        "outline-variant": "#3c4a42",
        "on-tertiary-fixed": "#40000d",
        "surface": "#051424",
        "surface-variant": "#273647",
        "on-tertiary": "#67001b",
        "inverse-surface": "#d4e4fa",
        "on-tertiary-fixed-variant": "#92002a",
        "surface-container-lowest": "#010f1f",
        "on-background": "#d4e4fa",
        "surface-container": "#122131",
        "background": "#051424",
        "error-container": "#93000a",
        "surface-container-high": "#1c2b3c",
        "surface-tint": "#4edea3",
        "error": "#ffb4ab",
        "on-primary-container": "#00422b",
        "secondary-fixed-dim": "#ffb95f",
        "inverse-on-surface": "#233143",
        "on-error-container": "#ffdad6",
        "outline": "#86948a",
        "primary-fixed-dim": "#4edea3",
        "primary-container": "#10b981",
        "secondary-container": "#ee9800",
        "on-secondary-fixed": "#2a1700",
        "surface-dim": "#051424",
        "on-tertiary-container": "#780021",
        "primary": "#4edea3",
        "surface-container-highest": "#273647"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "1rem",
        "gutter-desktop": "1.25rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1rem",
        "space-2xs": "0.125rem",
        "space-md": "0.75rem",
        "space-2xl": "2rem",
        "space-xl": "1.5rem",
        "space-sm": "0.5rem",
        "margin-desktop": "1.5rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "metric-display": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "label-caps": ["0.6875rem", { "lineHeight": "0.875rem", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "headline-lg": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-sm": ["1.125rem", { "lineHeight": "1.5rem", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-xl-mobile": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-code": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "metric-display": ["2rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "body-lg": ["1rem", { "lineHeight": "1.5rem", "fontWeight": "400" }],
        "body-sm": ["0.75rem", { "lineHeight": "1rem", "fontWeight": "400" }],
        "headline-xl": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.025em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
} satisfies Config
